#!/bin/bash

usage () {
    cat <<'EOF'

 ┌─┐┌─┐┌┬┐┌─┐┌┬┐┌─┐    ┬ ┬┌─┐┬ ┬─┐
 │  │ ││││├─┘ │ ├─┤ ── └┐││ ││ ├┬┘  v1.4
 └─┘└─┘┴ ┴┴   ┴ ┴ ┴     └┘└─┘┴ ┴└───────── 

Usage: compta-voir [OPTIONS]... [SEARCH]

  -a ACCOUNT    filter using given account name
                (Use quotes for multi words name ex: 'Monsieur Morbier')

  -b            Output the balance only
  -c CATEGORY   filter using one of the following category: don|infra|adhesion|autre
  -x            filter checked
  -u            filter unchecked
  -s COLUMN     sort by a column name (accents are mandatory)
  -r            revert sort order
  -t            output TSV without headers
  
  -h            print this help

SEARCH will look for matches into 'intitulé' column.

Git repo: <https://github.com/club-1/compta>
Club1 doc: <https://club1.fr/docs/fr/outils/compta.html>
EOF
}

output='pretty'

data=$(cat /var/compta/transactions.tsv)

while getopts 'a:bc:tuxs:rh' opt
do
    case $opt in
        a)
            name="$OPTARG"
            data=$(echo "$data" | awk -F $'\t' -v name="$name" '$4 ~ name')
        ;;

        b)
            output='balance'
        ;;

        c)
            if [ "$OPTARG" = 'don' ] || [ "$OPTARG" = 'infra' ] || [ "$OPTARG" = 'adhesion' ] || [ "$OPTARG" = 'autre' ]
            then
                category="$OPTARG"
                data=$(echo "$data" | awk -F $'\t' -v category="$category" '$6==category')
            else
                echo "invalid category '${OPTARG}'"
                echo "valid categories are: don|infra|adhesion|autre"
                exit 1
            fi
        ;;
        
        t)
            output='tsv'
        ;;

        u)
            data=$(echo "$data" | awk -F $'\t' '$5==""')
        ;;

        x)
            data=$(echo "$data" | awk -F $'\t' '$5=="x"')
        ;;

        s)
            num='' # numerical sorting flag
            case "$OPTARG" in
                id)        sort=1; num='-g' ;;
                date)      sort=2; num='-g' ;;
                montant)   sort=3; num='-g' ;;
                compte)    sort=4 ;;
                effectué)  sort=5 ;;
                catégorie) sort=6 ;;
                intitulé)  sort=7 ;;
                *)
                    echo "invalid sort column name '${OPTARG}'"
                    usage
                    exit 1
                    ;;
            esac
            data=$(echo "$data" | sort -t $'\t' -k $sort $num)
        ;;

        r)
            data=$(echo "$data" | tac)
        ;;

        h)
            usage
            exit
		;;
        
        ?)
            usage
            exit 1
		;;
    esac
done

shift "$(($OPTIND -1))"

data=$(echo "$data" | awk -F $'\t' -v name="$1" 'tolower($7) ~ tolower(name)')


case $output in
    'tsv')
        echo "$data"
        exit
    ;;

    'balance')
        echo "$data" | cut -f 3 | awk '{t=t+$1} END{print t}'
        exit
    ;;

    'pretty')
        echo "$data" | column -N id,date,montant,compte,effectué,catégorie,intitulé -R montant -ts $'\t'
        echo '════════════════════════════════════════════════════════════════════════════════════════════════════'
        balance=$(echo "$data" | cut -f 3 | awk '{t=t+$1} END{print t}')
        lineCount=$(echo "$data" | wc -l)
        echo "    balance :     $balance €                                                   ($lineCount entrées)"
        exit
    ;;
esac
