#!/bin/bash

export PS3="Entrez le numéro correspondant :"
IFS=$'\n'
data=$(cat /var/compta/transactions.tsv)
comptes=$(cut -f 4 /var/compta/transactions.tsv | sort -u)
comptes=$'tout voir\n'$comptes
# unset -v IFS

echo '🏷️  Quelle catégorie ?'
select categorie in 'tout voir' 'adhesion' 'infra' 'don' 'autre'
do
    echo '--------------------------------------------------'
    if [[ $REPLY -ne 1 ]]
    then
        filtercategory=true
        data=$(echo "$data" | awk -F $'\t' -v categorie="$categorie" '$6==categorie')	#filtre les entrées par nom ducompte
    else
        filtercategory=false
    fi

break
done


echo '👥 Voulez vous filtrer les comptes ?'
select name in $comptes
do
    echo '--------------------------------------------------'
    if [[ $REPLY -eq 1 ]]
    then
        filteraccount=false
    else
        filteraccount=true
        data=$(echo "$data" | awk -F $'\t' -v name="$name" '$4==name')	#filtre les entrées par nom ducompte
    fi

break
done


echo '🔩 Options supplémentaires'
select option in 'peu importe' 'seulement les transactions effectués' 'seulement les transactions pas encore effectués'
do
    echo '--------------------------------------------------'
    case $option in
        'peu importe')
            filterchecked=false
            ;;
        'seulement les transactions effectués')
            filterchecked=true
            data=$(echo "$data" | awk -F $'\t' '$5=="x"')
            ;;
        'seulement les transactions pas encore effectués')
            filterchecked=true
            data=$(echo "$data" | awk -F $'\t' '$5==""')
            ;;
    esac
break
done

cat <<EOF

 ┌──────────────────────────────────────────────────────────────────────────┐ 
 │           💰️           T R A N S A C T I O N S             📈            │ 
 └──────────────────────────────────────────────────────────────────────────┘ 

EOF

if [ "$filtercategory" = true ]
then
    echo "🏷️  parmis la catégorie '${categorie}'"
fi

if [ "$filteraccount" = true ]
then
    echo "👥 vers le compte de ${name}"
fi

if [ "$filterchecked" = true ]
then
    echo "✅ ${option}"
fi

echo
echo "$data" | column -N id,date,montant,compte,effectué,catégorie,intitulé -ts $'\t'
echo
echo -e "⚖️  \033[1mbalance :\033[00m"
echo "$data" | cut -f 3 | awk '{t=t+$1} END{print t}'
echo
