#!/bin/bash

usage () {
    cat <<'EOF'

 ┌─┐┌─┐┌┬┐┌─┐┌┬┐┌─┐    ┌─┐ ┬┌─┐┬ ┬┌┬┐┌─┐┬─┐
 │  │ ││││├─┘ │ ├─┤ -- ├─┤ ││ ││ │ │ ├┤ ├┬┘
 └─┘└─┘┴ ┴┴   ┴ ┴ ┴    ┴ ┴└┘└─┘└─┘ ┴ └─┘┴└─

Usage: compta-ajouter [OPTION]...
  
  -a ACCOUNT    account name - Optional if transaction is not checked
  -c CATEGORY   one of the following category: don|infra|adhesion|autre
  -d DATE       date in YYYY-MM-DD format - Optional: if not set, today is used
  -i INFO       info
  -m MONTANT    montant
  -x            check - Optional
  -y            do not ask for confirmation

  -h            print this help

Source code: <https://github.com/club-1/compta>
EOF
}

if test ! -w /var/compta/transactions.tsv 
then
    exit 2
fi

while getopts 'a:c:d:i:m:xyh' opt
do
    case $opt in
        a)
            account="$OPTARG"
        ;;

        c)
            if [ "$OPTARG" = 'don' ] || [ "$OPTARG" = 'infra' ] || [ "$OPTARG" = 'adhesion' ] || [ "$OPTARG" = 'autre' ]
            then
                category="$OPTARG"
            else
                echo "invalid category argument '${OPTARG}'"
                exit 1
            fi
        ;;

        d)
            if [[ $OPTARG =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] && date -d "$OPTARG" "+%Y-%m-%d" >/dev/null 2>&1
            then
                date="$OPTARG"
            else
                echo "invalid date argument '${OPTARG}'"
                exit 1
            fi
        ;;

        i)
            info="$OPTARG"
        ;;

        m)
            if [[ $OPTARG =~ ^[-+][0-9]+$ ]]
            then
                montant="$OPTARG"
            else
                echo "invalid montant argument '${OPTARG}'"
                exit 1
            fi
        ;;

        x)
            check='x'
        ;;

        y)
            yes='yes'
        ;;

        h)
            usage
            exit
		;;
        
        ?)
            usage
            exit 1
		;;
    esac
done

# shift "$(($OPTIND -1))"

if test -z "$category"
then
    echo 'category have to be set'
    exit 1
fi

if test -z "$info"
then
    echo 'info have to be set'
    exit 1
fi

if test -n "$check" && test -z "$account" 
then
    echo 'account have to be set if transaction is checked'
    exit 1
fi

lastId=$(cut -f 1 /var/compta/transactions.tsv | tail -n 1)
id=$(($lastId + 1))

if test -z "$date"
then
    date=$(date +%Y-%m-%d)
fi


trans="$id	$date	$montant	$account	$check	$category	$info"

if test -n "$yes"
then
    echo "$trans" >> /var/compta/transactions.tsv
    exit
fi


echo "$trans" | column -N id,date,montant,nom,effectué,catégorie,intitulé -ts $'\t'
echo '----------------------------------------------------'
echo "✒️  Voulez vous ajouter cette transaction ? (oui/non)"
read consent
case $consent in

    yes | oui | o | y)
        echo "$trans" >> /var/compta/transactions.tsv
        exit $?
    ;;
    *)
    effectue=''
        exit 130
    ;;

esac
