#!/bin/bash

cat <<-EOF

  ██████╗ ██████╗ ███╗   ███╗██████╗ ████████╗ █████╗     
 ██╔════╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔══██╗    
 ██║     ██║   ██║██╔████╔██║██████╔╝   ██║   ███████║    
 ██║     ██║   ██║██║╚██╔╝██║██╔═══╝    ██║   ██╔══██║    
 ╚██████╗╚██████╔╝██║ ╚═╝ ██║██║        ██║   ██║  ██║    
  ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝        ╚═╝   ╚═╝  ╚═╝ de CLUB1   

EOF

export PS3="Entrez le numéro correspondant :"



voir() {
    echo '🏷️  Quelle catégorie ?'
    select filtercategory in 'tout' 'adhesion' 'infra' 'don' 'autre'
    do
        echo '--------------------------------------------------'
        if [[ $REPLY -ne 1 ]]
        then
            category="$filtercategory"
        fi

    break
    done


    accounts=('tout')
    readarray -t -s1 -O1 accounts <<< $(cut -f 4 /var/compta/transactions.tsv | sort -u)
    echo '👥 Voulez vous filtrer les comptes ?'
    select filteraccount in "${accounts[@]}"
    do
        echo '--------------------------------------------------'
        if [[ $REPLY -ne 1 ]]
        then
            account="$filteraccount"
        fi

    break
    done


    echo '🔩 Options supplémentaires'
    select option in 'non' 'effectué' 'non effectué'
    do
        echo '--------------------------------------------------'
        case $option in
            'effectué')
                check='x'
            ;;

            'non effectué')
                check='u'
            ;;
        esac
    break
    done

    cat <<EOF

┌──────────────────────────────────────────────────────────────────────────┐ 
│           💰️           T R A N S A C T I O N S             📈            │ 
└──────────────────────────────────────────────────────────────────────────┘ 

EOF

    args=()

    if test -n "$category"
    then
        args+=('-c' "$category")
        echo "🗂️  parmis la catégorie '$category'"
    fi

    if test -n "$account"
    then
        args+=('-a' "$account")
        echo "👥 vers le compte de $account"
    fi

    if test -n "$check"
    then
        args+=("-$check")
        echo "✅ $option"
    fi

    args+=('-t')
    data=$(compta-voir "${args[@]}")

    echo
    echo "$data" | column -N id,date,montant,compte,effectué,catégorie,intitulé -ts $'\t'
    echo
    echo -e "⚖️  \033[1mbalance :\033[00m"
    echo "$data" | cut -f 3 | awk '{t=t+$1} END{print t}'
    echo
}


ajouter () {
    args=()

    echo "📝 C'est parti pout ajouter une nouvelle transaction !"
    echo '==================================================='
    echo '(Vous pouvez annuler à tout moment en tapant CTRL + C)'

    echo "📅 à quelle date ? (au format YYYY-MM-DD) lasser vide pour aujourd'hui"
    read date
    if test -z date
    then
        args+=('-d' "$date")
    fi

    echo "💶 Quel montant ? (indiquer + ou - devant le nombre)"
    read argent
    args+=('-m' "$argent")

    echo "💰 compte ayant reçu l'argent ?"
    accounts=('on ne sait pas encore' 'créer un nouveau compte')
    readarray -t -s1 -O2 accounts <<< $(cut -f 4 /var/compta/transactions.tsv | sort -u)
    select account in "${accounts[@]}"
    do echo "vous avez choisi $account"
    break
    done
    if test "$account" != 'on ne sait pas encore'
    then
        if test "$account" == 'créer un nouveau compte'
        then
            echo '👤 nom du nouveau compte ?'
            read account
        fi
        args+=('-a' "$account")
    fi

    echo "✅ le paiement a-t-il été effectué ? (oui/non)"
    read effectue
    case $effectue in
        yes | oui | o | y)
            args+=('-x')
            echo 'effectué'
        ;;

        *)
            echo 'pas encore effectué'
        ;;
    esac

    echo "🗂️  Quelle catégorie ?"
    select categorie in adhesion infra don autre
    do echo "vous avez choisi $categorie"
    break
    done
    args+=('-c' "$categorie")

    echo "🏷️  intitulé ?"
    read info
    args+=('-i' "$info")

    echo '🧾 Résumé de la transaction :'
    compta-ajouter "${args[@]}"

    case $? in
        0)
            echo "✨ Transaction ajoutée ! Merci $USER et bonne journée"
            ;;
        130)
            echo "🗑️  transaction annulée"
            ;;
        *)
            echo "⛔️ Erreur lors de l'ajoute de la transaction"
            ;;
    esac

}



echo "🛎️  Bienvenue $USER. Que voulez vous faire ?"
select action in 'voir les comptes' 'ajouter une transaction' 'quitter'
do
    echo '--------------------------------------------------'
    case $action in

        'voir les comptes')
            voir
        ;;

        'ajouter une transaction')
            if id -nG "$USER" | grep -qw 'compta'
            then
                ajouter
            else
                echo "Désolé, c'est impossible 😟"
                echo "Pour ajouter une transaction, il faut être membre du groupe 'compta'"
            fi

            
        ;;

        'quitter')
        echo '👋 À la prochaine !'

    esac


break
done
